services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: no
    env_file:
      - ../common/hadoop.env
    environment:
      - CLUSTER_NAME=bigdata-lab
    ports:
      - "9870:9870"
      - "8020:8020"
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: no
    env_file:
      - ../common/hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    ports:
      - "9864:9864"
    depends_on:
      - namenode
    networks:
      - bigdata-net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    restart: no
    env_file:
      - ../common/hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    ports:
      - "9865:9864"
    depends_on:
      - namenode
    networks:
      - bigdata-net

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    hostname: datanode3
    restart: no
    env_file:
      - ../common/hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    ports:
      - "9866:9864"
    depends_on:
      - namenode
    networks:
      - bigdata-net

networks:
  bigdata-net:
    external: true